name: Test

on:
  push:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Node version
    - name: Use Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'

    # Install Node modules
    - run: npm ci

    # Run unit tests
    - run: npm test
      env:
        CI: true

    # Run build
    - run: npm run build
