name: Run Tests

# run on pull requests to main branch
on:
  pull_request:
    branches:
      - main

# cancel previous tests if new commit is pushed to PR branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - run: npm ci

      - run: npm test
